# Site settings
title: Tibor Stanko
email: contact@tiborstanko.sk
description: > # this means to ignore newlines until "baseurl:"
  music, maths &amp; webdesign .
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://tiborstanko.sk # the base hostname & protocol for your site
enforce_ssl: tiborstanko.sk # without any protocol

twitter_username: tiborstanko
github_username:  bbrrck
lastfm_username: boberr
goodreads_username: 6403898-tibor-stanko
instagram_username : bbrrck
linkedin_cc: sk
linkedin_username: tiborstanko 

# Navigation
links:
- url: /publications/
  title: publications
#- url: /teaching/
#  title: teaching
- url: /posts/
  title: blog

# Outputting
permalink: none

# Build settings
markdown: kramdown