# Site settings
title: Tibor Stanko
email: "&#116;&#105;&#098;&#111;&#114;&#046;&#115;&#116;&#097;&#110;&#107;&#111;&#064;{&#032;&#099;&#101;&#097;,&#032;&#105;&#110;&#114;&#105;&#097;,&#032;&#117;&#110;&#105;&#118;&#045;&#103;&#114;&#101;&#110;&#111;&#098;&#108;&#101;&#045;&#097;&#108;&#112;&#101;&#115;&#032;}&#046;&#102;&#114;"
description: "music, maths &amp; webdesign."
baseurl: ""
url: https://tiborstanko.sk # the base hostname & protocol for your site
enforce_ssl: tiborstanko.sk # without any protocol
future: false
permalink: none
markdown: kramdown
highlighter: rouge

twitter_username: tiborstanko
github_username:  bbrrck
lastfm_username: boberr
goodreads_username: 6403898-tibor-stanko
instagram_username : bbrrck
linkedin_cc: sk
linkedin_username: tiborstanko 

# Navigation
links:
- url: /publications/
  title: publications
- url: /teaching/
  title: teaching
- url: /posts/
  title: blog
