# Site settings
baseurl: ""
description: "music, maths &amp; webdesign."
email: "&#116;&#105;&#098;&#111;&#114;&#046;&#115;&#116;&#097;&#110;&#107;&#111;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"
emailall: "&#116;&#105;&#098;&#111;&#114;&#046;&#115;&#116;&#097;&#110;&#107;&#111;&#032;&#064;&#032;{&#032;&#105;&#110;&#114;&#105;&#097;,&#032;&#099;&#101;&#097;,&#032;&#117;&#110;&#105;&#118;&#045;&#103;&#114;&#101;&#110;&#111;&#098;&#108;&#101;&#045;&#097;&#108;&#112;&#101;&#115;&#032;}&#032;&#046;&#032;&#102;&#114;"
enforce_ssl: tiborstanko.sk # without any protocol
exclude:
  - [vendor]
  - Gemfile
  - Gemfile.lock
  - vendor
future: false
highlighter: rouge
markdown: kramdown
paginate: 5
paginate_path: /posts/:num/
permalink: none
safe: true
title: Tibor Stanko
url: https://tiborstanko.sk # the base hostname & protocol for your site

# Navigation
links:
- url: /publications/
  title: publications
- url: /posts/
  title: blog
- url: /teaching/
  title: teaching

# Bib + Social nets
bibindent: "  "
twitter_username: tiborstanko
github_username:  bbrrck
lastfm_username: boberr
goodreads_username: 6403898-tibor-stanko
instagram_username : bbrrck
linkedin_cc: sk
linkedin_username: tiborstanko
