# Site settings
title: Tibor Stanko
email: "&#099;&#111;&#110;&#116;&#097;&#099;&#116;&#064;&#116;&#105;&#098;&#111;&#114;&#115;&#116;&#097;&#110;&#107;&#111;&#046;&#115;&#107;"
description: "music, maths &amp; webdesign."
baseurl: ""
url: https://tiborstanko.sk # the base hostname & protocol for your site
enforce_ssl: tiborstanko.sk # without any protocol
future: false
permalink: none
markdown: kramdown
#highlighter: rouge

twitter_username: tiborstanko
github_username:  bbrrck
lastfm_username: boberr
goodreads_username: 6403898-tibor-stanko
instagram_username : bbrrck
linkedin_cc: sk
linkedin_username: tiborstanko 

# Navigation
links:
- url: /publications/
  title: publications
- url: /teaching/geo-num-2016/
  title: teaching
- url: /posts/
  title: blog
