# Site settings
# inria email: &#116;&#105;&#098;&#111;&#114;&#046;&#115;&#116;&#097;&#110;&#107;&#111;&#064;&#105;&#110;&#114;&#105;&#097;&#046;&#102;&#114;
# gmail email: &#116;&#105;&#098;&#111;&#114;&#046;&#115;&#116;&#097;&#110;&#107;&#111;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;
baseurl: ""
description: "music, maths &amp; webdesign."
email: "&#116;&#105;&#098;&#111;&#114;&#046;&#115;&#116;&#097;&#110;&#107;&#111;&#064;&#105;&#110;&#114;&#105;&#097;&#046;&#102;&#114;"
enforce_ssl: tiborstanko.sk # without any protocol
exclude:
  - [vendor]
  - Gemfile
  - Gemfile.lock
  - vendor
future: false

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  # # More › http://kramdown.gettalong.org/quickref.html
  # # Options › http://kramdown.gettalong.org/options.html
  # # https://github.com/jekyll/jekyll/pull/4090
  # syntax_highlighter: rouge
  # # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # # span, block element options fall back to global
  # syntax_highlighter_opts:
  #   # Rouge Options › https://github.com/jneen/rouge#full-options
  #   css_class: 'highlight'
  #   #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
  #   span:
  #     line_numbers: false
  #   block:
  #     line_numbers: true
  #     start_line: 1

excerpt_separator: <!--more-->

paginate: 10
paginate_path: /posts/:num/
permalink: none
safe: true
title: Tibor Stanko
url: https://tiborstanko.sk # the base hostname & protocol for your site

# Navigation
links:
# - url: /#news
#   title: news
# - url: /#publications
#   title: publications
# - url: /#bio
#   title: bio
# - url: /#teaching
#   title: teaching
- url: /posts/
  title: blog

# Bib + Social nets
bibindent: "  "
twitter_username: tiborstanko
github_username:  bbrrck
lastfm_username: boberr
goodreads_username: 6403898-tibor-stanko
instagram_username : bbrrck
linkedin_cc: sk
linkedin_username: tiborstanko

# plugins:
# - jekyll-twitter-plugin
